### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tadrian** [nielsbosma/pivotpad#1]
Could you provide better example with some sample data, thanks!

![image](https://user-images.githubusercontent.com/3002124/207308466-140a8a21-52c7-4b82-9e99-b62fbf38e82e.png)

**Comment by nielsbosma** [comment]
The Pivot function doesn't return anything (void). Just remove the "var d = " in your code.

**Comment by tadrian** [comment]
ok, thanks that explains it, I just followed the example in the readme :-)
